trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
container: 
    image: nowicki.azurecr.io/scala-build:latest
    endpoint: nowicki


steps:
- task: Npm@1
  inputs:
    workingDir: 'frontend'
    command: 'install'
- task: Npm@1
  inputs:
    workingDir: 'frontend'
    command: 'custom'
    customCommand: 'run build'
- script: sbt docker:publishLocal
  displayName: 'Compile scala and build docker'
- task: Docker@2
  inputs:
    containerRegistry: 'nowicki'
    repository: 'nowicki/camera-interface-system'
    command: 'push'
    tags: 'latest'
- script: curl -i https://marisa.maciejnowicki.com:16443 || true
  displayName: 'testing connectivity'
- task: Kubernetes@1
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'marisa'
    command: 'rollout'
    arguments: 'restart deployment/camera-interface-system'

