trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
container: 
    image: nowicki.azurecr.io/scala-build:latest
    endpoint: nowicki


steps:
- script: sbt docker:publishLocal
  displayName: 'Compile scala and build docker'
- task: Docker@2
  inputs:
    containerRegistry: 'nowicki'
    repository: 'camera-interface-system'
    command: 'push'
    tags: 'latest'